export const AVATAR_LIST_REQUEST = 'AVATAR_LIST_REQUEST';
export const AVATAR_LIST_SUCCESS = 'AVATAR_LIST_SUCCESS';
export const AVATAR_LIST_FAIL = 'AVATAR_LIST_FAIL';

export const AVATAR_CREATE_REQUEST = 'AVATAR_CREATE_REQUEST';
export const AVATAR_CREATE_SUCCESS = 'AVATAR_CREATE_SUCCESS';
export const AVATAR_CREATE_FAIL = 'AVATAR_CREATE_FAIL';
export const AVATAR_CREATE_RESET = 'AVATAR_CREATE_RESET';

export const AVATAR_UPDATE_REQUEST = 'AVATAR_UPDATE_REQUEST';
export const AVATAR_UPDATE_SUCCESS = 'AVATAR_UPDATE_SUCCESS';
export const AVATAR_UPDATE_FAIL = 'AVATAR_UPDATE_FAIL';
export const AVATAR_UPDATE_RESET = 'AVATAR_UPDATE_RESET';

export const AVATAR_DELETE_REQUEST = 'AVATAR_DELETE_REQUEST';
export const AVATAR_DELETE_SUCCESS = 'AVATAR_DELETE_SUCCESS';
export const AVATAR_DELETE_FAIL = 'AVATAR_DELETE_FAIL';
