export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_EDIT_REQUEST = 'PRODUCT_EDIT_REQUEST';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_FAIL = 'PRODUCT_EDIT_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_DELETE_OPTION_REQUEST = 'PRODUCT_DELETE_OPTION_REQUEST';
export const PRODUCT_DELETE_OPTION_SUCCESS = 'PRODUCT_DELETE_OPTION_SUCCESS';
export const PRODUCT_DELETE_OPTION_FAIL = 'PRODUCT_DELETE_OPTION_FAIL';
export const PRODUCT_DELETE_OPTION_RESET = 'PRODUCT_DELETE_OPTION_RESET';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_OPTIONCOLOR_REQUEST = 'PRODUCT_OPTIONCOLOR_REQUEST';
export const PRODUCT_OPTIONCOLOR_SUCCESS = 'PRODUCT_OPTIONCOLOR_SUCCESS';
export const PRODUCT_OPTIONCOLOR_FAIL = 'PRODUCT_OPTIONCOLOR_FAIL';
export const PRODUCT_OPTIONCOLOR_RESET = 'PRODUCT_OPTIONCOLOR_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_UPDATE_OPTION_REQUEST = 'PRODUCT_UPDATE_OPTION_REQUEST';
export const PRODUCT_UPDATE_OPTION_SUCCESS = 'PRODUCT_UPDATE_OPTION_SUCCESS';
export const PRODUCT_UPDATE_OPTION_FAIL = 'PRODUCT_UPDATE_OPTION_FAIL';
export const PRODUCT_UPDATE_OPTION_RESET = 'PRODUCT_UPDATE_OPTION_RESET';

export const PRODUCT_LIST_COMMENT_ALL_REQUEST = 'PRODUCT_LIST_COMMENT_ALL_REQUEST';
export const PRODUCT_LIST_COMMENT_ALL_SUCCESS = 'PRODUCT_LIST_COMMENT_ALL_SUCCESS';
export const PRODUCT_LIST_COMMENT_ALL_FAIL = 'PRODUCT_LIST_COMMENT_ALL_FAIL';
export const PRODUCT_LIST_COMMENT_ALL_RESET = 'PRODUCT_LIST_COMMENT_ALL_RESET';

export const PRODUCT_CREATE_COMMENTCHILD_REQUEST = 'PRODUCT_CREATE_COMMENTCHILD_REQUEST';
export const PRODUCT_CREATE_COMMENTCHILD_SUCCESS = 'PRODUCT_CREATE_COMMENTCHILD_SUCCESS';
export const PRODUCT_CREATE_COMMENTCHILD_FAIL = 'PRODUCT_CREATE_COMMENTCHILD_FAIL';
export const PRODUCT_CREATE_COMMENTCHILD_RESET = 'PRODUCT_CREATE_COMMENTCHILD_RESET';
