export const SLIDER_LIST_REQUEST = "SLIDER_LIST_REQUEST";
export const SLIDER_LIST_SUCCESS = "SLIDER_LIST_SUCCESS";
export const SLIDER_LIST_FAIL = "SLIDER_LIST_FAIL";

export const SLIDER_CREATE_REQUEST = "SLIDER_CREATE_REQUEST";
export const SLIDER_CREATE_SUCCESS = "SLIDER_CREATE_SUCCESS";
export const SLIDER_CREATE_FAIL = "SLIDER_CREATE_FAIL";
export const SLIDER_CREATE_RESET = "SLIDER_CREATE_RESET";

export const SLIDER_UPDATE_REQUEST = "SLIDER_UPDATE_REQUEST";
export const SLIDER_UPDATE_SUCCESS = "SLIDER_UPDATE_SUCCESS";
export const SLIDER_UPDATE_FAIL = "SLIDER_UPDATE_FAIL";
export const SLIDER_UPDATE_RESET = "SLIDER_UPDATE_RESET";

export const SLIDER_DELETE_REQUEST = "SLIDER_DELETE_REQUEST";
export const SLIDER_DELETE_SUCCESS = "SLIDER_DELETE_SUCCESS";
export const SLIDER_DELETE_FAIL = "SLIDER_DELETE_FAIL";