export const NEWS_LIST_REQUEST = 'NEWS_LIST_REQUEST';
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS';
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL';

export const NEWS_GET_REQUEST = 'NEWS_GET_REQUEST';
export const NEWS_GET_SUCCESS = 'NEWS_GET_SUCCESS';
export const NEWS_GET_FAIL = 'NEWS_GET_FAIL';
