export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

export const ORDER_ADDRESS_MY_REQUEST = 'ORDER_ADDRESS_MY_REQUEST';
export const ORDER_ADDRESS_MY_SUCCESS = 'ORDER_ADDRESS_MY_SUCCESS';
export const ORDER_ADDRESS_MY_FAIL = 'ORDER_ADDRESS_MY_FAIL';
export const ORDER_ADDRESS_MY_RESET = 'ORDER_ADDRESS_MY_RESET';

export const ORDER_LIST_ALL_REQUEST = 'ORDER_LIST_ALL_REQUEST';
export const ORDER_LIST_ALL_SUCCESS = 'ORDER_LIST_ALL_SUCCESS';
export const ORDER_LIST_ALL_FAIL = 'ORDER_LIST_ALL_FAIL';

export const ORDER_CANCEL_REQUEST = 'ORDER_CANCEL_REQUEST';
export const ORDER_CANCEL_SUCCESS = 'ORDER_CANCEL_SUCCESS';
export const ORDER_CANCEL_FAIL = 'ORDER_CANCEL_FAIL';
export const ORDER_CANCEL_RESET = 'ORDER_CANCEL_RESET';

export const ORDER_CREATE_REVIEW_REQUEST = 'ORDER_CREATE_REVIEW_REQUEST';
export const ORDER_CREATE_REVIEW_SUCCESS = 'ORDER_CREATE_REVIEW_SUCCESS';
export const ORDER_CREATE_REVIEW_FAIL = 'ORDER_CREATE_REVIEW_FAIL';
export const ORDER_CREATE_REVIEW_RESET = 'ORDER_CREATE_REVIEW_RESET';

export const ORDER_GET_REVIEW_REQUEST = 'ORDER_GET_REVIEW_REQUEST';
export const ORDER_GET_REVIEW_SUCCESS = 'ORDER_GET_REVIEW_SUCCESS';
export const ORDER_GET_REVIEW_FAIL = 'ORDER_GET_REVIEW_FAIL';

export const ORDER_COMPLETE_USER_REQUEST = 'ORDER_COMPLETE_USER_REQUEST';
export const ORDER_COMPLETE_USER_SUCCESS = 'ORDER_COMPLETE_USER_SUCCESS';
export const ORDER_COMPLETE_USER_FAIL = 'ORDER_COMPLETE_USER_FAIL';
export const ORDER_COMPLETE_USER_RESET = 'ORDER_COMPLETE_USER_RESET';

export const ORDER_RETURN_AMOUNT_PRODUCT_REQUEST = 'ORDER_  RETURN_AMOUNT_PRODUCT_REQUEST';
export const ORDER_RETURN_AMOUNT_PRODUCT_SUCCESS = 'ORDER_  RETURN_AMOUNT_PRODUCT_SUCCESS';
export const ORDER_RETURN_AMOUNT_PRODUCT_FAIL = 'ORDER_ RETURN_AMOUNT_PRODUCT_FAIL';
export const ORDER_RETURN_AMOUNT_PRODUCT_RESET = 'ORDER_RETURN_AMOUNT_PRODUCT_RESET';
