export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_LIST_ALL_REQUEST = 'PRODUCT_LIST_ALL_REQUEST';
export const PRODUCT_LIST_ALL_SUCCESS = 'PRODUCT_LIST_ALL_SUCCESS';
export const PRODUCT_LIST_ALL_FAIL = 'PRODUCT_LIST_ALL_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';

export const PRODUCT_CREATE_COMMENT_REQUEST = 'PRODUCT_CREATE_COMMENT_REQUEST';
export const PRODUCT_CREATE_COMMENT_SUCCESS = 'PRODUCT_CREATE_COMMENT_SUCCESS';
export const PRODUCT_CREATE_COMMENT_FAIL = 'PRODUCT_CREATE_COMMENT_FAIL';
export const PRODUCT_CREATE_COMMENT_RESET = 'PRODUCT_CREATE_COMMENT_RESET';

export const PRODUCT_CREATE_COMMENTCHILD_REQUEST = 'PRODUCT_CREATE_COMMENTCHILD_REQUEST';
export const PRODUCT_CREATE_COMMENTCHILD_SUCCESS = 'PRODUCT_CREATE_COMMENTCHILD_SUCCESS';
export const PRODUCT_CREATE_COMMENTCHILD_FAIL = 'PRODUCT_CREATE_COMMENTCHILD_FAIL';
export const PRODUCT_CREATE_COMMENTCHILD_RESET = 'PRODUCT_CREATE_COMMENTCHILD_RESET';
